useClickOutside hook - nova usabilidade
naveteam/prometheus pull request #6
Opened 2020-07-28 14:54 UTC by sblucas97

## Descrição
O código foi alterado para ser possível utilizar mais de uma referência na funcionalidade esperada (quantas forem necessárias).

## Existe tratamento de erro?
Sim.

## Breaking changes?
Não.

## Novo story adicionado?
Sim.

2020-07-28 17:19 UTC, rcandia submitted a review, later dismissed

2020-07-28 21:06 UTC, eduardobittencourt requested changes

2020-07-28 21:06 UTC, eduardobittencourt commented on src/hooks/useClickOutside.js
> +        const needToHandle = refs.filter(ref => !ref.current || ref.current.contains(event.target))
sugestão: utilizar o método `some` ao invés de `filter` para evitar a necessidade de testar o length do array logo abaixo

2020-07-29 12:02 UTC, eduardobittencourt approved these changes

2020-07-29 12:31 UTC, merged

2020-07-29 12:59 UTC, eduardobittencourt commented
@all-contributors please add @sblucas97 for code doc

2020-07-29 13:08 UTC, eduardobittencourt commented
@all-contributors please add @rcandia for review